### ISSUE TITLE
r886: Crash during mod loading

### ISSUE THREAD

**Issue by EzerArch** [Eximius88/ModularPowersuitsAddons#6] opened 2014-05-02 03:23 UTC
Minecraft Version: 1.6.4
Forge Version: 9.11.1.965-MCPatcher
MPS Version: 1.6.4-0.10.0-91 or 100
Numina Version:0.1.2-55 or 57

The game crash during mod loading. I removed all other mods and kept MPS and MPSA.
- Forge log: http://pastebin.com/g8D95Pjx

**Comment by Eximius88** [comment] 2014-05-03 06:49
Please post a pastebin link to the crash report located in the crash-reports folder. You posted the full forge log which spits out a TON of information that makes it very hard to find out what the problem is.

**Comment by EzerArch** [comment] 2014-05-03 07:10
No problem:
- http://pastebin.com/N2zmTmsZ

**Comment by Eximius88** [comment] 2014-05-03 16:24
It is an applied energistics issue. Do you have AE installed? I tested it with the latest DW20 and monster packs with no issues. Have you tried a fresh install? What mods are you using so I can try too reproduce this issue?

**Comment by Eximius88** [comment] 2014-05-03 18:48
Fixed in build 887. Closed.

**Closed as completed** 2014-05-03 18:48 UTC
