### ISSUE TITLE
Can't reload keybinds between sessions

### ISSUE THREAD

**Issue by EzerArch** [Eximius88/ModularPowersuitsAddons#17] opened 2014-10-13 23:57 UTC
MPSA version: 901

You can assign the keybinds at the Tinker Table but once you restart the game, the keybinds are lost.

**Comment by Eximius88** [comment] 2014-10-14 20:47
Weird. I explicitly tested this before release, and found no issues. Although, modules aren't configurable in the main MPS config. I will do more testing to see if I can replicate this.

**Comment by EzerArch** [comment] 2014-10-15 03:41
I tested again with no other mods, but with these:

ModularPowersuits-0.11.0.172.jar
Numina-0.4.0.98.jar
slick-util.jar
powersuitaddons-1.7.10-901.jar
CodeChickenCore-1.7.10-1.0.3.26-universal.jar
NotEnoughItems-1.7.10-1.0.3.56-universal.jar

And I assigned "Mob Repulsor" to "P" and "Magnet" to "U". Closed and reopened the game, the "U" and "P" keys are still there but floating without the module icons.

![2014-10-15_00 40 35](https://cloud.githubusercontent.com/assets/6743303/4640247/0a9ae082-541d-11e4-8379-a5b115e28115.png)

**Comment by Eximius88** [comment] 2014-10-28 05:37
Ok, working on this, since it should be an easy fix. I am at the point where I am going to re-write the mod from scratch, so I am working with code that I completely understand.

**Comment by Korynkai** [comment] 2014-11-29 01:22
Hmm, reminds me this has been an issue since my group was using Tekkit (1.6.4)... Will look into this as I've become rather familiar with the code for MPSA (and MPS itself for that matter), though I am wondering if @Eximius88 has any code that could potentially assist the fix that is not in Git as of yet... I have a massive feature PR coming along and I'll try to fix that as I continue my work on that (and I don't quite see a reason for a rewrite as of yet)...

**Comment by Korynkai** [comment] 2014-12-02 06:50
Already found the problem and fixed it in my internal build. 
The issue is in Modular Powersuits, not MPSA, it loads and parses the keybindings config before any other mod starts to load so MPSA doesn't have a chance to load its symbols, resulting in any keybindings for MPSA's modules pointing to null and therefore causing them to disassociate.
This will be fixed in my pull request to [MachineMuse/MachineMusePowersuits](https://github.com/MachineMuse/MachineMusePowersuits).

**Comment by Korynkai** [comment] 2014-12-02 09:45
This is fixed in the latest pull request at [MachineMuse/MachineMusePowersuits](https://github.com/MachineMuse/MachineMusePowersuits) or the latest commit at [QMXTech/MachineMusePowersuits](https://github.com/QMXTech/MachineMusePowersuits). This issue can be closed as soon as MachineMuse merges the pull request (or now, at @Eximius88's discretion).
Builds available here: [QMXTech/MachineMusePowersuits/releases](https://github.com/QMXTech/MachineMusePowersuits/releases)

**Closed as completed** 2017-03-01 02:07 UTC
